name: tasty-test-reporter
version: 0.1.1.4
synopsis: Producing JUnit-style XML test reports.
description: Please see the README at <https://github.com/stoeffel/tasty-test-reporter>.
author: Christoph Hermann
maintainer: schtoeffel@gmail.com
copyright: 2020 Christoph Hermann
homepage: https://github.com/stoeffel/tasty-test-reporter#readme
license-file: LICENSE
category: Testing
github: stoeffel/tasty-test-reporter
extra-doc-files:
- README.md
- CHANGELOG.md
library:
  dependencies:
  - ansi-terminal
  - base
  - concurrent-output
  - containers
  - directory
  - filepath
  - junit-xml
  - mtl
  - safe-exceptions
  - stm
  - tagged
  - tasty
  - text
  exposed-modules:
  - Test.Tasty.Runners.Reporter
  source-dirs: src
tests:
  spec:
    dependencies:
    - base
    - tasty
    - tasty-hunit
    - tasty-test-reporter
    main: Main.hs
    source-dirs:
    - test
